# Generated by Django 3.2.13 on 2022-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
